# Generated by Django 4.2.16 on 2025-06-19 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='C2Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('technology', models.CharField(blank=True, max_length=255, verbose_name='Технология')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_external', models.BooleanField(default=False, verbose_name='Внешний')),
            ],
            options={
                'verbose_name': 'Компонент C2',
                'verbose_name_plural': 'Компоненты C2',
            },
        ),
        migrations.CreateModel(
            name='C2GroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип группы C2',
                'verbose_name_plural': 'Типы групп C2',
            },
        ),
        migrations.CreateModel(
            name='C2Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('technology', models.CharField(blank=True, max_length=255, verbose_name='Технология')),
                ('format', models.CharField(blank=True, max_length=255, verbose_name='Формат')),
                ('component_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='architecture.c2component', verbose_name='Компонент источник')),
                ('component_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='architecture.c2component', verbose_name='Компонент назначение')),
            ],
            options={
                'verbose_name': 'Связь C2',
                'verbose_name_plural': 'Связи C2',
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип компонента',
                'verbose_name_plural': 'Типы компонентов',
            },
        ),
        migrations.CreateModel(
            name='DdGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('instances', models.IntegerField(blank=True, default=1, null=True, verbose_name='Количество экземпляров')),
                ('specification', models.TextField(blank=True, verbose_name='Спецификация')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='architecture.ddgroup', verbose_name='Родительская группа')),
            ],
            options={
                'verbose_name': 'Группа DD',
                'verbose_name_plural': 'Группы DD',
            },
        ),
        migrations.CreateModel(
            name='DdGroupType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип группы DD',
                'verbose_name_plural': 'Типы групп DD',
            },
        ),
        migrations.CreateModel(
            name='InfoObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Информационный объект',
                'verbose_name_plural': 'Информационные объекты',
            },
        ),
        migrations.CreateModel(
            name='OperationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тип операции',
                'verbose_name_plural': 'Типы операций',
            },
        ),
        migrations.AddField(
            model_name='ddgroup',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architecture.ddgrouptype', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='DdComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('technology', models.CharField(blank=True, max_length=255, verbose_name='Технология')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_external', models.BooleanField(default=False, verbose_name='Внешний')),
                ('c2_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='architecture.c2component', verbose_name='Компонент C2')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architecture.ddgroup', verbose_name='Группа')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architecture.componenttype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Компонент DD',
                'verbose_name_plural': 'Компоненты DD',
            },
        ),
        migrations.CreateModel(
            name='C2Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='architecture.c2group', verbose_name='Родительская группа')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architecture.c2grouptype', verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Группа C2',
                'verbose_name_plural': 'Группы C2',
            },
        ),
        migrations.AddField(
            model_name='c2component',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architecture.c2group', verbose_name='Группа'),
        ),
        migrations.AddField(
            model_name='c2component',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architecture.componenttype', verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='C2LinksInfoObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c2_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architecture.c2link', verbose_name='Связь C2')),
                ('infoobject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architecture.infoobject', verbose_name='Информационный объект')),
                ('operation_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architecture.operationtype', verbose_name='Тип операции')),
            ],
            options={
                'verbose_name': 'Связь C2 - Информационный объект',
                'verbose_name_plural': 'Связи C2 - Информационные объекты',
                'unique_together': {('c2_link', 'infoobject', 'operation_type')},
            },
        ),
    ]
