# Generated by Django 4.2.16 on 2025-06-19 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DdLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=255, verbose_name='Протокол')),
                ('group_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_links', to='architecture.ddgroup', verbose_name='Группа источник')),
                ('group_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_links', to='architecture.ddgroup', verbose_name='Группа назначение')),
            ],
            options={
                'verbose_name': 'Связь DD',
                'verbose_name_plural': 'Связи DD',
            },
        ),
        migrations.CreateModel(
            name='DdLinkPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.IntegerField(verbose_name='Порт')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Описание')),
                ('dd_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='architecture.ddlink', verbose_name='Связь DD')),
            ],
            options={
                'verbose_name': 'Порт связи DD',
                'verbose_name_plural': 'Порты связей DD',
                'unique_together': {('dd_link', 'port')},
            },
        ),
    ]
