# Generated by Django 4.2.16 on 2025-06-19 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0002_ddlink_ddlinkport'),
    ]

    operations = [
        migrations.CreateModel(
            name='DdLinkProtocol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Протокол связи DD',
                'verbose_name_plural': 'Протоколы связей DD',
            },
        ),
        migrations.RemoveField(
            model_name='ddlinkport',
            name='description',
        ),
        migrations.AlterField(
            model_name='ddlink',
            name='protocol',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='architecture.ddlinkprotocol', verbose_name='Протокол'),
        ),
    ]
