# Generated by Django 4.2.16 on 2025-06-20 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0003_ddlinkprotocol_remove_ddlinkport_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ddlink',
            old_name='protocol',
            new_name='protocol_id',
        ),
    ]
