# Generated by Django 4.2.16 on 2025-06-20 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('architecture', '0004_rename_protocol_ddlink_protocol_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ddlink',
            old_name='protocol_id',
            new_name='protocol',
        ),
    ]
